title = "https://YR-ZR0.github.io/'"
baseURL = 'https://YR-ZR0.github.io/'
languageCode = 'en-gb'
copyright= "James R (YR-ZR0)"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "./resources"


[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$','^asciidoctor$']

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true
show_reading_time = true

[languages]

  [languages.en]
    title = ""
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 1