title = "https://YR-ZR0.github.io/'"
baseURL = 'https://YR-ZR0.github.io/'
languageCode = 'en-gb'
copyright= "James R (YR-ZR0)"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "./resources"
disableKinds = ['rss']

[security]
  enableInlineShortcodes = false
  [security.exec]
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|GEM_PATH)$']
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$','^asciidoctor$']

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true
show_reading_time = true

[languages]

  [languages.en]
    title = ""
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
    text_color = "white"
    author = ""
    favicon = ""
    site_logo = ""
    description = ""
    background_color_class = "bg-near-black"
    body_classes = "avenir bg-near-black "
    recent_posts_number = 1
